apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-cloud
  description: 'backstage cloud on aws'
  annotations:
    github.com/project-slug: dhanu0001/backstage-cloud
    
spec:
  type: service
  lifecycle: experimental
  owner: user: dhanu0001
